#!/bin/sh

### BEGIN INIT INFO
# Provides:          Buildroot
# Required-Start:    $scull, $faulty, $hello
# Required-Stop:     $scull, $faulty, $hello
# Default-Start:     0 1 2
# Default-Stop:      0 1 2
# Short-Description: Load and unload scull, faulty, hello kernel modules
### END INIT INFO

cd /lib/modules/$(uname -r)/extra

case "$1" in
  start)
    echo "Loading misc-modules and scull drivers"
    module_load faulty
    modprobe hello
    scull_load
    aesdchar_load
    ;;
  stop)
    echo "Unloading misc-modules and scull drivers"
    scull_unload
    rmmod hello
    module_unload faulty
    aesdchar_unload
    ;;
  *)
    echo "Usage: $0 {start | stop}"
  exit 1
  esac

exit 0